// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdTtMW0BjhOE18aeNihRL6lKxhv1jdYn4',
    appId: '1:883727246703:web:834f86397a54db5229349a',
    messagingSenderId: '883727246703',
    projectId: 'getup-csc45',
    authDomain: 'getup-csc45.firebaseapp.com',
    storageBucket: 'getup-csc45.appspot.com',
    measurementId: 'G-8ZFKMPKDXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXYe2Uwgmu4GcA-C17UCQHgrTpwehj4NI',
    appId: '1:883727246703:android:6c2c5a55719d711429349a',
    messagingSenderId: '883727246703',
    projectId: 'getup-csc45',
    storageBucket: 'getup-csc45.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_wsD1tIMfjKok63VUa1xb-BmR1XUsvnA',
    appId: '1:883727246703:ios:6fe170b7363f0c9829349a',
    messagingSenderId: '883727246703',
    projectId: 'getup-csc45',
    storageBucket: 'getup-csc45.appspot.com',
    iosClientId: '883727246703-p8iejv7534r42vt29i3quu44lg0f4epm.apps.googleusercontent.com',
    iosBundleId: 'com.example.getupCsc450',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_wsD1tIMfjKok63VUa1xb-BmR1XUsvnA',
    appId: '1:883727246703:ios:1af22f8bc115302c29349a',
    messagingSenderId: '883727246703',
    projectId: 'getup-csc45',
    storageBucket: 'getup-csc45.appspot.com',
    iosClientId: '883727246703-e6m6smv2jhm9hjjk0dfvcmchtm31530v.apps.googleusercontent.com',
    iosBundleId: 'com.example.getupCsc450.RunnerTests',
  );
}
